namespace ClassFramework.TemplateFramework.Templates;

public sealed class CodeGenerationHeaderTemplate : CsharpClassGeneratorBase<CodeGenerationHeaderViewModel>, IStringBuilderTemplate
{
    public Task Render(StringBuilder builder, CancellationToken cancellationToken)
    {
        Guard.IsNotNull(builder);
        Guard.IsNotNull(Model);

        if (!Model.CreateCodeGenerationHeader)
        {
            return Task.CompletedTask;
        }

        builder.AppendLine($$"""
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: {{Model.Version}}
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
""");

        return Task.CompletedTask;
    }
}
