// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.5
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#nullable enable
namespace ClassFramework.Domain.Builders.CodeStatements
{
    public partial class StringCodeStatementBuilder : CodeStatementBaseBuilder<StringCodeStatementBuilder, ClassFramework.Domain.CodeStatements.StringCodeStatement>
    {
        private string _statement;

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public string Statement
        {
            get
            {
                return _statement;
            }
            set
            {
                _statement = value ?? throw new System.ArgumentNullException(nameof(value));
                HandlePropertyChanged(nameof(Statement));
            }
        }

        public StringCodeStatementBuilder(ClassFramework.Domain.CodeStatements.StringCodeStatement source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _statement = source.Statement;
        }

        public StringCodeStatementBuilder() : base()
        {
            _statement = string.Empty;
            SetDefaultValues();
        }

        public override ClassFramework.Domain.CodeStatements.StringCodeStatement BuildTyped()
        {
            return new ClassFramework.Domain.CodeStatements.StringCodeStatement(Statement);
        }

        partial void SetDefaultValues();

        public ClassFramework.Domain.Builders.CodeStatements.StringCodeStatementBuilder WithStatement(string statement)
        {
            if (statement is null) throw new System.ArgumentNullException(nameof(statement));
            Statement = statement;
            return this;
        }
    }
}
#nullable disable
