// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace ClassFramework.TemplateFramework
{
    public partial record CsharpClassGeneratorSettings : CrossCutting.Common.Abstractions.IBuildableEntity<ClassFramework.TemplateFramework.Builders.CsharpClassGeneratorSettingsBuilder>
    {
        public bool RecurseOnDeleteGeneratedFiles
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        public string LastGeneratedFilesFilename
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Text.Encoding Encoding
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        public string Path
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Globalization.CultureInfo CultureInfo
        {
            get;
        }

        public bool GenerateMultipleFiles
        {
            get;
        }

        public bool SkipWhenFileExists
        {
            get;
        }

        public bool CreateCodeGenerationHeader
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        public string EnvironmentVersion
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        public string FilenameSuffix
        {
            get;
        }

        public bool EnableNullableContext
        {
            get;
        }

        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool EnableNullablePragmas
        {
            get;
        }

        public bool EnableGlobalUsings
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Collections.Generic.IReadOnlyCollection<string> CustomUsings
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Collections.Generic.IReadOnlyCollection<string> NamespacesToAbbreviate
        {
            get;
        }

        public CsharpClassGeneratorSettings(bool recurseOnDeleteGeneratedFiles, string lastGeneratedFilesFilename, System.Text.Encoding encoding, string path, System.Globalization.CultureInfo cultureInfo, bool generateMultipleFiles, bool skipWhenFileExists, bool createCodeGenerationHeader, string environmentVersion, string filenameSuffix, bool enableNullableContext, bool enableNullablePragmas, bool enableGlobalUsings, System.Collections.Generic.IEnumerable<string> customUsings, System.Collections.Generic.IEnumerable<string> namespacesToAbbreviate)
        {
            this.RecurseOnDeleteGeneratedFiles = recurseOnDeleteGeneratedFiles;
            this.LastGeneratedFilesFilename = lastGeneratedFilesFilename;
            this.Encoding = encoding;
            this.Path = path;
            this.CultureInfo = cultureInfo;
            this.GenerateMultipleFiles = generateMultipleFiles;
            this.SkipWhenFileExists = skipWhenFileExists;
            this.CreateCodeGenerationHeader = createCodeGenerationHeader;
            this.EnvironmentVersion = environmentVersion;
            this.FilenameSuffix = filenameSuffix;
            this.EnableNullableContext = enableNullableContext;
            this.EnableNullablePragmas = enableNullablePragmas;
            this.EnableGlobalUsings = enableGlobalUsings;
            this.CustomUsings = customUsings is null ? null! : new CrossCutting.Common.ReadOnlyValueCollection<System.String>(customUsings);
            this.NamespacesToAbbreviate = namespacesToAbbreviate is null ? null! : new CrossCutting.Common.ReadOnlyValueCollection<System.String>(namespacesToAbbreviate);
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator ClassFramework.TemplateFramework.Builders.CsharpClassGeneratorSettingsBuilder(ClassFramework.TemplateFramework.CsharpClassGeneratorSettings entity)
        {
            return entity.ToBuilder();
        }

        public ClassFramework.TemplateFramework.Builders.CsharpClassGeneratorSettingsBuilder ToBuilder()
        {
            return new ClassFramework.TemplateFramework.Builders.CsharpClassGeneratorSettingsBuilder(this);
        }
    }
}
#nullable disable
