// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace ClassFramework.TemplateFramework.Tests
{
    public partial record TestEntity : CrossCutting.Common.Abstractions.IBuildableEntity<ClassFramework.TemplateFramework.Tests.Builders.TestEntityBuilder>
    {
        public string SingleProperty
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        public System.Collections.Generic.IReadOnlyCollection<string> CollectionProperty
        {
            get;
        }

        public TestEntity(string singleProperty, System.Collections.Generic.IEnumerable<string> collectionProperty)
        {
            this.SingleProperty = singleProperty;
            this.CollectionProperty = collectionProperty is null ? null! : new CrossCutting.Common.ReadOnlyValueCollection<System.String>(collectionProperty);
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public static implicit operator ClassFramework.TemplateFramework.Tests.Builders.TestEntityBuilder(ClassFramework.TemplateFramework.Tests.TestEntity entity)
        {
            return entity.ToBuilder();
        }

        public ClassFramework.TemplateFramework.Tests.Builders.TestEntityBuilder ToBuilder()
        {
            return new ClassFramework.TemplateFramework.Tests.Builders.TestEntityBuilder(this);
        }
    }
}
#nullable disable
